#pragma once

enum
{
	IDS_PNAME_IM = 1000,
	IDS_PHELP_IM,

	IDS_PNAME_IM_SELECT,
	IDS_PHELP_IM_SELECT,


	IDS_PNAME_IM_CREATE,
	IDS_PHELP_IM_CREATE,

	IDS_PNAME_IM_RENAME,
	IDS_PHELP_IM_RENAME,


	IDS_PNAME_IM_SPLIT,
	IDS_PHELP_IM_SPLIT,

	IDS_PNAME_IM_MAKEEDITABLE,
	IDS_PHELP_IM_MAKEEDITABLE,

	IDS_PNAME_IM_SWAP,
	IDS_PHELP_IM_SWAP,

	IDS_PNAME_IM_FRAMEOBJECTS,
	IDS_PHELP_IM_FRAMEOBJECTS,

	IDS_PNAME_IM_FRAMEELEMENTS,
	IDS_PHELP_IM_FRAMEELEMENTS,


	IDS_SETTINGSDIALOG_TITLE,
	IDS_LBL_INSTANCEMODE,
	IDS_INSTANCEMODE,

	IDS_REFCOUNTWARN,

	_DUMMY_ELEMENT_
};
